// WI-136 Phase 6 — bundled Google Fonts snapshot ("모든 폰트 찾아보기" backend).
//
// The curated FONT_CATALOG is the default browse surface; this snapshot is the
// WIDER set a user can reach via "모든 폰트 찾아보기". It is a STATIC bundle (no
// Google Fonts API key, no runtime quota, no CORS) — regenerate periodically
// from the Google Fonts Developer API and replace SNAPSHOT below. Selecting a
// font here builds an ad-hoc FontEntry (makeGoogleFontEntry) and loads it on
// demand; the stored value is the literal stack (a per-item override).
//
// Compact tuple form: [family, category, korean?]. Catalog duplicates are kept
// out by `GOOGLE_FONTS_SNAPSHOT` filtering against FONT_BY_ID.

import {
  FONT_BY_ID,
  type FontCategory,
  type FontEntry,
  fontIdFromFamily,
  makeGoogleFontEntry,
} from "./catalog.js";

type SnapshotRow = readonly [family: string, category: FontCategory, korean?: true];

const SNAPSHOT: ReadonlyArray<SnapshotRow> = [
  // Sans
  ["Roboto", "sans"],
  ["Open Sans", "sans"],
  ["Lato", "sans"],
  ["Montserrat", "sans"],
  ["Poppins", "sans"],
  ["Inter", "sans"],
  ["Noto Sans", "sans"],
  ["Nunito", "sans"],
  ["Nunito Sans", "sans"],
  ["Rubik", "sans"],
  ["Work Sans", "sans"],
  ["Mukta", "sans"],
  ["Karla", "sans"],
  ["Quicksand", "sans"],
  ["Barlow", "sans"],
  ["Mulish", "sans"],
  ["Heebo", "sans"],
  ["DM Sans", "sans"],
  ["Manrope", "sans"],
  ["Hind", "sans"],
  ["Cabin", "sans"],
  ["Josefin Sans", "sans"],
  ["Titillium Web", "sans"],
  ["Oxygen", "sans"],
  ["Fira Sans", "sans"],
  ["PT Sans", "sans"],
  ["Source Sans 3", "sans"],
  ["Archivo", "sans"],
  ["Public Sans", "sans"],
  ["Outfit", "sans"],
  ["Plus Jakarta Sans", "sans"],
  ["Figtree", "sans"],
  ["Lexend", "sans"],
  ["Sora", "sans"],
  ["Space Grotesk", "sans"],
  ["Red Hat Display", "sans"],
  ["Assistant", "sans"],
  ["Kanit", "sans"],
  ["Signika", "sans"],
  ["Jost", "sans"],
  // Serif
  ["Merriweather", "serif"],
  ["Playfair Display", "serif"],
  ["Lora", "serif"],
  ["PT Serif", "serif"],
  ["Noto Serif", "serif"],
  ["Roboto Slab", "serif"],
  ["Bitter", "serif"],
  ["Crimson Text", "serif"],
  ["Libre Baskerville", "serif"],
  ["Cormorant Garamond", "serif"],
  ["EB Garamond", "serif"],
  ["Source Serif 4", "serif"],
  ["Spectral", "serif"],
  ["Domine", "serif"],
  ["Zilla Slab", "serif"],
  ["Frank Ruhl Libre", "serif"],
  ["Vollkorn", "serif"],
  ["Cardo", "serif"],
  ["Arvo", "serif"],
  ["Bodoni Moda", "serif"],
  ["DM Serif Display", "serif"],
  ["Newsreader", "serif"],
  // Mono
  ["Roboto Mono", "mono"],
  ["JetBrains Mono", "mono"],
  ["Source Code Pro", "mono"],
  ["Fira Code", "mono"],
  ["IBM Plex Mono", "mono"],
  ["Space Mono", "mono"],
  ["Inconsolata", "mono"],
  ["Ubuntu Mono", "mono"],
  ["PT Mono", "mono"],
  ["Overpass Mono", "mono"],
  ["DM Mono", "mono"],
  ["Red Hat Mono", "mono"],
  // Display
  ["Oswald", "display"],
  ["Bebas Neue", "display"],
  ["Anton", "display"],
  ["Archivo Black", "display"],
  ["Abril Fatface", "display"],
  ["Righteous", "display"],
  ["Fjalla One", "display"],
  ["Teko", "display"],
  ["Comfortaa", "display"],
  ["Lobster", "display"],
  ["Pacifico", "display"],
  ["Bungee", "display"],
  ["Staatliches", "display"],
  ["Alfa Slab One", "display"],
  ["Passion One", "display"],
  ["Russo One", "display"],
  ["Saira Condensed", "display"],
  ["Bangers", "display"],
  // Handwriting
  ["Caveat", "handwriting"],
  ["Dancing Script", "handwriting"],
  ["Pacifico", "handwriting"],
  ["Shadows Into Light", "handwriting"],
  ["Satisfy", "handwriting"],
  ["Great Vibes", "handwriting"],
  ["Kalam", "handwriting"],
  ["Sacramento", "handwriting"],
  ["Permanent Marker", "handwriting"],
  ["Indie Flower", "handwriting"],
  ["Amatic SC", "handwriting"],
  ["Courgette", "handwriting"],
  ["Cookie", "handwriting"],
  ["Gloria Hallelujah", "handwriting"],
  // Korean
  ["Noto Sans KR", "sans", true],
  ["Noto Serif KR", "serif", true],
  ["Nanum Gothic", "sans", true],
  ["Nanum Myeongjo", "serif", true],
  ["Nanum Gothic Coding", "mono", true],
  ["IBM Plex Sans KR", "sans", true],
  ["Gowun Dodum", "sans", true],
  ["Gowun Batang", "serif", true],
  ["Black Han Sans", "display", true],
  ["Do Hyeon", "display", true],
  ["Jua", "display", true],
  ["Gugi", "display", true],
  ["Black And White Picture", "display", true],
  ["Sunflower", "sans", true],
  ["Hahmlet", "serif", true],
  ["Gaegu", "handwriting", true],
  ["Nanum Pen Script", "handwriting", true],
  ["Nanum Brush Script", "handwriting", true],
  ["Single Day", "handwriting", true],
  ["Dokdo", "handwriting", true],
  ["Poor Story", "handwriting", true],
  ["Song Myung", "serif", true],
  ["Stylish", "sans", true],
  ["Cute Font", "display", true],
];

/** Browse-surface entries (curated catalog removed, so the dialog only shows
 *  fonts not already in the main picker). Built once at module load. */
export const GOOGLE_FONTS_SNAPSHOT: ReadonlyArray<FontEntry> = SNAPSHOT.filter(
  ([family]) => !FONT_BY_ID.has(fontIdFromFamily(family)),
).map(([family, category, korean]) =>
  makeGoogleFontEntry(family, category, korean === true ? ["latin", "korean"] : ["latin"]),
);
